name: yascm

version: 0.1.0.0

ghc-options:
  - -Wall

default-extensions:
  - OverloadedStrings
  - TemplateHaskell
  - QuasiQuotes
  - ScopedTypeVariables
  - PatternSynonyms
  - NamedFieldPuns
  - NoImplicitPrelude # https://github.com/commercialhaskell/stack/issues/5077

dependencies:
  # - name: base
  #   mixin:
  #     - hiding (Prelude)
  # - name: relude
  #   mixin:
  #     - (Relude as Prelude)
  # - type-operators
  - relude
  - base
  - containers
  - parsec
  - haskeline
  - optparse-applicative
  - transformers
  - either
  - placeholders
  - text
  - text-format
  - string-conversions
  - raw-strings-qq
  - optics

executables:
  yascm-app:
    main: Main.hs
    source-dirs: app/
    dependencies:
      - yascm

library:
  source-dirs: src/
  exposed-modules:
    - EvalApply
    - Parser
    - Repl
    - ScmPrelude
    - Types

tests:
  yascm-test:
    main: Spec.hs
    source-dirs: test/
    dependencies:
      - yascm
      - hspec
